# Generated by Django 4.0.3 on 2022-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='チーム名')),
                ('rank', models.CharField(max_length=50, verbose_name='ランク帯')),
            ],
            options={
                'verbose_name_plural': '募集チーム',
            },
        ),
        migrations.AlterModelOptions(
            name='createteam',
            options={'verbose_name_plural': 'チーム募集（仮）'},
        ),
        migrations.AlterField(
            model_name='createteam',
            name='rank',
            field=models.CharField(max_length=50, verbose_name='ランク帯'),
        ),
        migrations.AlterField(
            model_name='createteam',
            name='team_name',
            field=models.CharField(max_length=50, verbose_name='チーム名'),
        ),
    ]
